package com.orelzman.mydialer.domain.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

@Entity
/**
 * [CallId] - Is the ID generated by the server
 * [date] - The date when the call started
 * [duration] - Time of call in milliseconds
 *
 * @author Orel Zilberman, 6.11.2021
 */
data class Call(
    @PrimaryKey val CallId: String,
    @ColumnInfo val date: Date,
    @ColumnInfo val duration: Long,
    @ColumnInfo val isActive: Boolean
) {

}